package com.ksjd.testem.ui.theme

import androidx.compose.ui.graphics.Color

val DarkBackground = Color(0xFF0B0D10)
val DarkSurface = Color(0xFF12151A)
val DarkSurfaceVariant = Color(0xFF1B2027)
val DarkOutline = Color(0xFF2A313A)
val DarkPrimary = Color(0xFF29D3C6)
val DarkSecondary = Color(0xFF6B7C93)
val DarkTertiary = Color(0xFF3E4C5C)
val DarkOnBackground = Color(0xFFE9EDF2)
val DarkOnSurface = Color(0xFFE9EDF2)
val DarkOnSurfaceVariant = Color(0xFFB0BBC7)
val DarkPrimaryContainer = Color(0xFF103B39)
val DarkOnPrimary = Color(0xFF001D1C)
val DarkOnPrimaryContainer = Color(0xFFB8FFF8)
val DarkSecondaryContainer = Color(0xFF1B2733)
val DarkOnSecondaryContainer = Color(0xFFD7E2F0)
val DarkError = Color(0xFFE34D59)
val DarkErrorContainer = Color(0xFF3A1015)
val DarkOnError = Color(0xFFFFF5F6)
val DarkOnErrorContainer = Color(0xFFFFDAD9)

val LightBackground = Color(0xFFF4F6F9)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFE9EDF2)
val LightOutline = Color(0xFFD0D7E2)
val LightPrimary = Color(0xFF0EA5A2)
val LightSecondary = Color(0xFF4D5A6A)
val LightTertiary = Color(0xFF7A8797)
val LightOnBackground = Color(0xFF0B0D10)
val LightOnSurface = Color(0xFF0B0D10)
val LightOnSurfaceVariant = Color(0xFF5B6674)
val LightPrimaryContainer = Color(0xFFBFF3EF)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightOnPrimaryContainer = Color(0xFF003A38)
val LightSecondaryContainer = Color(0xFFE1E7F0)
val LightOnSecondaryContainer = Color(0xFF1B2733)
val LightError = Color(0xFFE5484D)
val LightErrorContainer = Color(0xFFFBD7D9)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410006)